# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tabular_lib',
                'doc_host': 'https://andreazza.github.io',
                'git_url': 'https://github.com/andreazza/tabular_lib',
                'lib_path': 'tabular_lib'},
  'syms': { 'tabular_lib.core': {'tabular_lib.core.foo': ('core.html#foo', 'tabular_lib/core.py')},
            'tabular_lib.tab': { 'tabular_lib.tab.TabData': ('core.html#tabdata', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.__init__': ('core.html#tabdata.__init__', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.convert_to_date': ('core.html#tabdata.convert_to_date', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.create_tab_obj': ('core.html#tabdata.create_tab_obj', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.exp_dep_var': ('core.html#tabdata.exp_dep_var', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.get_train_valid_idxs_time_series': ( 'core.html#tabdata.get_train_valid_idxs_time_series',
                                                                                               'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.handling_dates': ('core.html#tabdata.handling_dates', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.log_dep_var': ('core.html#tabdata.log_dep_var', 'tabular_lib/tab.py'),
                                 'tabular_lib.tab.TabData.preprocess_ordinal': ( 'core.html#tabdata.preprocess_ordinal',
                                                                                 'tabular_lib/tab.py')}}}