# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tabular_lib',
                'doc_host': 'https://andreazza.github.io',
                'git_url': 'https://github.com/andreazza/tabular_lib',
                'lib_path': 'tabular_lib'},
  'syms': {'tabular_lib.core': {'tabular_lib.core.foo': ('core.html#foo', 'tabular_lib/core.py')}}}